# Generated by Django 4.2.7 on 2025-07-26 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
    ]
